use_frameworks!

platform :ios, '9.0'

target 'HXMultiThread_Example' do
  pod 'HXMultiThread', :path => '../'
  pod 'AFNetworking', '4.0.1'
  
  target 'HXMultiThread_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
